AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CloudFormation template for creating the S3 bucket for Lambda code deployment.

Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-code-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  LambdaCodeBucketName:
    Description: The name of the S3 bucket for Lambda code
    Value: !Ref LambdaCodeBucket
    Export:
      Name: !Sub "${AWS::StackName}-LambdaCodeBucketName"
