AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CloudFormation template for creating the InstaBot Secrets Manager secret.

Resources:
  InstaBotSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${AWS::StackName}-InstaBotSecrets"
      Description: "Stores secrets for the InstaBot application."
      SecretString: '{
        "InstagramUsername": "YOUR_USERNAME_HERE",
        "InstagramPassword": "YOUR_PASSWORD_HERE",
        "ReceiverEmail": "receiver@example.com",
        "Client1": "client_name_here",
        "Client1Email": "client@example.com",
        "api_key": "YOUR_API_KEY_HERE",
        "api_key_2": "YOUR_API_KEY_HERE",
        "api_key_3": "YOUR_API_KEY_HERE",
        "api_key_4": "YOUR_API_KEY_HERE",
        "api_key_5": "YOUR_API_KEY_HERE",
        "api_host": "YOUR_API_HOST_HERE",
        "content_type": "application/json",
        "sender_email": "YOUR_SENDER_EMAIL_HERE",
        "sender_password": "YOUR_SENDER_PASSWORD_HERE"
      }'

Outputs:
  SecretARN:
    Description: The ARN of the InstaBot secret
    Value: !Ref InstaBotSecrets
    Export:
      Name: !Sub "${AWS::StackName}-SecretARN"
  SecretName:
    Description: The Name of the InstaBot secret
    Value: !Sub "${AWS::StackName}-InstaBotSecrets"
    Export:
      Name: !Sub "${AWS::StackName}-SecretName"
